
package medimage.views;

import java.util.List;
import medimage.models.Connection;
import medimage.models.Study;

/**
 * View for choosing a study to open when the application starts.
 * @author col32
 */
public class DefaultStudyView extends javax.swing.JDialog {
    
    /**
     * Wrapper for study that toString's null studies into "No Default"
     */
    private class StudyWrapper {
        StudyWrapper(Study s) {
            this.study = s;
        }
        
        Study study;
        
        @Override
        public String toString() {
            if(study == null)
                return "No Default";
            return study.toString();
        }
    }
    
    private final Connection connection;
    
    /**
     * Creates new form DefaultStudyView
     * @param parent
     * @param conn Connection object to choose default study from.
     */
    public DefaultStudyView(java.awt.Frame parent, Connection conn) {
        super(parent, true);
        initComponents();
        connection = conn;
        
        Study currentlySelected = connection.getDefaultStudy();
        List<Study> studies = connection.getStudies();
        
        // Create array of wrappers.
        StudyWrapper[] arr = new StudyWrapper[studies.size()+1];
        
        // Set 'No Default' element
        arr[0] = new StudyWrapper(null);
        
        // Set the rest
        for(int i=0; i<studies.size(); i++) {
            arr[i+1] = new StudyWrapper(studies.get(i));
        }
        
        // Set studies
        studySelector.setListData(arr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel headerLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane sudyScroller = new javax.swing.JScrollPane();
        studySelector = new javax.swing.JList<StudyWrapper>();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headerLabel.setText("Select study to open on application start:");

        studySelector.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sudyScroller.setViewportView(studySelector);

        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerLabel)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(sudyScroller)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sudyScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Callback for the cancel button. Exits the dialog without saving.
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /**
     * Callback for the save button. Saves the settings.
     * @param evt 
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        connection.saveDefaultStudy(studySelector.getSelectedValue().study);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JList<StudyWrapper> studySelector;
    // End of variables declaration//GEN-END:variables
}
