
package medimage.views;

import javax.swing.ButtonModel;
import medimage.models.Study;

/**
 *
 * @author col32
 */
public class ReconstructionOptionsView extends javax.swing.JDialog {
    
    
    private final java.awt.Frame parent;
    private final Study study;
    
    /**
     * Creates new form ReconstructionOptionsView
     * @param parent
     * @param study
     */
    public ReconstructionOptionsView(java.awt.Frame parent, Study study) {
        super(parent, true);
        this.parent = parent;
        this.study = study;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        axisGroup = new javax.swing.ButtonGroup();
        viewButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        javax.swing.JLabel label = new javax.swing.JLabel();
        xAxisRadio = new javax.swing.JRadioButton();
        yAxisRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reconstruction Options");
        setResizable(false);

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        label.setText("Select Axis");

        axisGroup.add(xAxisRadio);
        xAxisRadio.setText("Sagittal (Slices are left to right)");

        axisGroup.add(yAxisRadio);
        yAxisRadio.setSelected(true);
        yAxisRadio.setText("Coronal (Slices are top to bottom)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yAxisRadio)
                    .addComponent(xAxisRadio)
                    .addComponent(label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xAxisRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yAxisRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        this.dispose();
        ReconstructionView recon = new ReconstructionView(this.parent, this.study, xAxisRadio.isSelected());
        recon.setVisible(true);
    }//GEN-LAST:event_viewButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup axisGroup;
    private javax.swing.JButton backButton;
    private javax.swing.JButton viewButton;
    private javax.swing.JRadioButton xAxisRadio;
    private javax.swing.JRadioButton yAxisRadio;
    // End of variables declaration//GEN-END:variables
}
