
package medimage.views;

import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.ImageIcon;
import medimage.models.Image;
import medimage.models.Study;

/**
 * View for reconstructions.
 * @author col32
 */
public class ReconstructionView extends javax.swing.JDialog {
    
    public enum Axis {
        
    }
    
    // Colors
    private final int COLOR_RED = 0x00ff0000;
    private final int COLOR_GREEN = 0x0000ff00;
    private final int COLOR_BLUE = 0x000000ff;
    
    /**
     * Study that is being viewed.
     */
    private final Study study;
    
    /**
     * Image data.
     * Coordinates are data[x][y][z] with x going to the right, y going up,
     * and z going out of the xy plane.
     */
    private final int[][][] data;
    
    /**
     * Currently viewed slices.
     */
    private int sliceX, sliceY, sliceZ;
    
    /**
     * Creates new form ReconstructionView
     * @param parent
     * @param study
     * @param isSagattal
     */
    public ReconstructionView(java.awt.Frame parent, Study study, boolean isSagattal) {
        super(parent, true);
        initComponents();
        
        this.study = study;
        
        List<Image> images = study.getImages();
        
        BufferedImage baseImg = images.get(0).getImageData();
        if(isSagattal)
            data = new int[images.size()][baseImg.getWidth()][baseImg.getHeight()];
        else
            data = new int[baseImg.getWidth()][images.size()][baseImg.getHeight()];
        
        for(int i=0; i<images.size(); i++) {
            BufferedImage d = images.get(i).getImageData();
            
            if(isSagattal) {
                for(int x=0; x<d.getWidth(); x++)
                    for(int y=0; y<d.getHeight(); y++)
                        data[i][x][y] = d.getRGB(x, y);
            }
            else {
                for(int x=0; x<d.getWidth(); x++)
                    for(int y=0; y<d.getHeight(); y++)
                        data[x][images.size()-i-1][y] = d.getRGB(x, y);
            }
        }
        
        updateUI();
    }
    
    /**
     * Updates the UI.
     */
    private void updateUI() {
        BufferedImage top = new BufferedImage(data.length, data[0][0].length, BufferedImage.TYPE_INT_RGB);
        BufferedImage front = new BufferedImage(data.length, data[0].length, BufferedImage.TYPE_INT_RGB);
        BufferedImage side = new BufferedImage(data[0][0].length, data[0].length, BufferedImage.TYPE_INT_RGB);
        
        // Construct top view from data.
        for(int x=0; x<data.length; x++)
            for(int z=0; z<data[0][0].length; z++) {
                int color;
                if(x == sliceX)
                    color = COLOR_RED;
                else if(z == sliceZ)
                    color = COLOR_BLUE;
                else
                    color = data[x][sliceY][z];
                top.getRaster().setSample(x, z, 0, color);
            }
        
        // Construct front view.
        for(int x=0; x<data.length; x++)
            for(int y=0; y<data[0].length; y++) {
                int color;
                if(x == sliceX)
                    color = COLOR_RED;
                else if(y == sliceY)
                    color = COLOR_GREEN;
                else
                    color = data[x][y][sliceZ];
                front.getRaster().setSample(x, y, 0, color);
            }
        
        // Construct side view.
        for(int y=0; y<data[0].length; y++)
            for(int z=0; z<data[0][0].length; z++) {
                int color;
                if(y == sliceY)
                    color = COLOR_GREEN;
                else if(z == sliceZ)
                    color = COLOR_BLUE;
                else
                    color = data[sliceX][y][z];
                side.getRaster().setSample(z, y, 0, color);
            }
        
        // Display images
        topImage.setIcon(new ImageIcon(top));
        frontImage.setIcon(new ImageIcon(front));
        sideImage.setIcon(new ImageIcon(side));
        
        topImage.setText("");
        frontImage.setText("");
        sideImage.setText("");
        
        this.pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel imagesContainer = new javax.swing.JPanel();
        javax.swing.JPanel topImageContainer = new javax.swing.JPanel();
        topImage = new javax.swing.JLabel();
        topScrollLeftButton = new javax.swing.JButton();
        topScrollRightButton = new javax.swing.JButton();
        javax.swing.JPanel frontImageContainer = new javax.swing.JPanel();
        frontImage = new javax.swing.JLabel();
        frontScrollLeftButton = new javax.swing.JButton();
        frontScrollRightButton = new javax.swing.JButton();
        javax.swing.JPanel sideImageContainer = new javax.swing.JPanel();
        sideImage = new javax.swing.JLabel();
        sideScrollLeftButton = new javax.swing.JButton();
        sideScrollRightButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reconstruction");

        imagesContainer.setLayout(new java.awt.GridLayout(2, 2));

        topImage.setText("<image>");

        topScrollLeftButton.setText("<");

        topScrollRightButton.setText(">");

        javax.swing.GroupLayout topImageContainerLayout = new javax.swing.GroupLayout(topImageContainer);
        topImageContainer.setLayout(topImageContainerLayout);
        topImageContainerLayout.setHorizontalGroup(
            topImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topImageContainerLayout.createSequentialGroup()
                        .addComponent(topScrollLeftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(topScrollRightButton)))
                .addContainerGap())
        );
        topImageContainerLayout.setVerticalGroup(
            topImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topImage, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topScrollLeftButton)
                    .addComponent(topScrollRightButton))
                .addContainerGap())
        );

        imagesContainer.add(topImageContainer);

        frontImage.setText("<image>");

        frontScrollLeftButton.setText("<");

        frontScrollRightButton.setText(">");

        javax.swing.GroupLayout frontImageContainerLayout = new javax.swing.GroupLayout(frontImageContainer);
        frontImageContainer.setLayout(frontImageContainerLayout);
        frontImageContainerLayout.setHorizontalGroup(
            frontImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frontImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frontImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frontImageContainerLayout.createSequentialGroup()
                        .addComponent(frontScrollLeftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(frontScrollRightButton)))
                .addContainerGap())
        );
        frontImageContainerLayout.setVerticalGroup(
            frontImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frontImage, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frontImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frontScrollLeftButton)
                    .addComponent(frontScrollRightButton))
                .addContainerGap())
        );

        imagesContainer.add(frontImageContainer);

        sideImage.setText("<image>");

        sideScrollLeftButton.setText("<");

        sideScrollRightButton.setText(">");

        javax.swing.GroupLayout sideImageContainerLayout = new javax.swing.GroupLayout(sideImageContainer);
        sideImageContainer.setLayout(sideImageContainerLayout);
        sideImageContainerLayout.setHorizontalGroup(
            sideImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sideImageContainerLayout.createSequentialGroup()
                        .addComponent(sideScrollLeftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(sideScrollRightButton)))
                .addContainerGap())
        );
        sideImageContainerLayout.setVerticalGroup(
            sideImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideImageContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideImage, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sideImageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sideScrollLeftButton)
                    .addComponent(sideScrollRightButton))
                .addContainerGap())
        );

        imagesContainer.add(sideImageContainer);

        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel frontImage;
    private javax.swing.JButton frontScrollLeftButton;
    private javax.swing.JButton frontScrollRightButton;
    private javax.swing.JLabel sideImage;
    private javax.swing.JButton sideScrollLeftButton;
    private javax.swing.JButton sideScrollRightButton;
    private javax.swing.JLabel topImage;
    private javax.swing.JButton topScrollLeftButton;
    private javax.swing.JButton topScrollRightButton;
    // End of variables declaration//GEN-END:variables
}
