
package medimage.views.improvedimageview;

import java.util.List;
import javax.swing.JLabel;
import medimage.ImageIterator;
import medimage.QuadImageIterator;
import medimage.models.DisplayState;
import medimage.models.Image;

/**
 *
 * @author col32
 */
public class QuadImagePanel extends ImagePanel {

    /**
     * Creates new form QuadImagePanel
     */
    public QuadImagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_1 = new javax.swing.JLabel();
        image_2 = new javax.swing.JLabel();
        image_3 = new javax.swing.JLabel();
        image_4 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(2, 2));

        image_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_1.setText("(Image 1)");
        add(image_1);

        image_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_2.setText("(Image 2)");
        add(image_2);

        image_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_3.setText("(Image 3)");
        add(image_3);

        image_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_4.setText("(Image 4)");
        add(image_4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image_1;
    private javax.swing.JLabel image_2;
    private javax.swing.JLabel image_3;
    private javax.swing.JLabel image_4;
    // End of variables declaration//GEN-END:variables

    @Override
    protected DisplayState getDisplayState(ImageIterator iter) {
        return new DisplayState(DisplayState.States.QUAD_IMAGE, iter.getIndex());
    }

    @Override
    protected JLabel[] getImageContainers() {
        return new JLabel[] {
            image_1,
            image_2,
            image_3,
            image_4
        };
    }

    @Override
    protected ImageIterator createIterator(List<Image> images, int index) {
        return new QuadImageIterator(images, index);
    }
    
    @Override
    protected boolean isReadOnly() {
        return false;
    }
}
