
package medimage.views.improvedimageview;

import java.util.List;
import javax.swing.JLabel;
import medimage.ImageIterator;
import medimage.SingleImageIterator;
import medimage.models.DisplayState;
import medimage.models.Image;

/**
 *
 * @author col32
 */
public class SingleImagePanel extends ImagePanel {

    /**
     * Creates new form SingleImageView
     */
    public SingleImagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 1));

        image_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_1.setText("(Image 1)");
        add(image_1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image_1;
    // End of variables declaration//GEN-END:variables
    
    @Override
    protected JLabel[] getImageContainers() {
        return new JLabel[] { image_1 };
    }

    @Override
    protected ImageIterator createIterator(List<Image> images, int index) {
        return new SingleImageIterator(images, index);
    }

    @Override
    protected boolean isReadOnly() {
        return false;
    }
}
